[game]
starting_level = {{cookiecutter.starting_level}}
num_lives = {{cookiecutter.num_lives}}
music_volume = 80
effects_volume = 80
debug = false
god_mode = false
max_window_height = {{cookiecutter.window_height}}
sprite_scale = 1.0

[background]
background_image = "assets/images/background.png"
star_count = 300
star_speed_min = 20.0
star_speed_max = 120.0

[ui]
popup_duration = 0.8
popup_rise_speed = 60.0
